spring:
  application:
    name: langchain4j
server:
  port: 8080
hailiang:
  langchain4j:
    # ?????
    llm:
      # ???
      provider-name: openai
      # ???
      model-name: gpt-3.5-turbo
      # url
      base-url: https://api.chatanywhere.tech/v1
      # api-key
      api-key: sk-gRbZ9FJz2E7c7mwO5JOvp2u2rtoWoAbg12CxDy3Y25eLeDvd
    # ????
    embedding:
      # ???
      provider-name: openai
      # api-key
      api-key: sk-gRbZ9FJz2E7c7mwO5JOvp2u2rtoWoAbg12CxDy3Y25eLeDvd
      # url
      base-url: https://api.chatanywhere.tech/v1
      store:
        elastic-host: 154.204.60.125
        elastic-port: 9200
        elastic-username: elastic
        elastic-password: admin8989
        index-name: langchain